name: Geo Jolly
title: Geo Jolly | Developer
description: >-
  Geo Jolly | Developer 
  member @amFOSS
baseurl: ""
url: "https://kingjuno.me"
cover: /assets/img/cover.png
email: geojollyc@gmail.com
twitter: https://twitter.com/king__juno
instagram: https://instagram.com/geo__jolly
github: https://github.com/kingjuno
linkedin: https://www.linkedin.com/in/geo-jolly
permalink: pretty
markdown: kramdown

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

gems:
  - jekyll-feed
  - jekyll-autoprefixer

exclude:
  - Gemfile.lock
  - Gemfile

sass:
  sass_dir: _sass